### ISSUE TITLE
"another transaction on channel: {ID: 20} is in progress"

### ISSUE THREAD

**Issue by arturgontijo** [singnet/snet-daemon#172]
Hi guys, I have a channel to call `basic-service` that I had published a time ago.
Its state:
```
$ snet client get_channel_state 20 54.203.198.53:7002
current_nonce                  = 0
current_signed_amount_in_cogs  = 5
current_unspent_amount_in_cogs = 106
```

But when I call the service using it, I'm getting this error:
```
$ snet client call 20 0.00000001 54.203.198.53:7002 mul '{"a":15,"b":78}'
unspent_amount_in_cogs before call (None means that we cannot get it now):106
Error: <_Rendezvous of RPC that terminated with:
	status = StatusCode.FAILED_PRECONDITION
	details = "another transaction on channel: {ID: 20} is in progress"
	debug_error_string = "{"created":"@1544558848.135429276","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"another transaction on channel: {ID: 20} is in progress","grpc_status":9}"
>
If you want to see full Traceback then run:
snet --print-traceback [parameters]
```

Then I opened a new channel and the call function worked fine:
```
$ snet client call 181 0.00000001 54.203.198.53:7002 mul '{"a":15,"b":78}'
unspent_amount_in_cogs before call (None means that we cannot get it now):1
value: 1170.0
```

What I have to do to "terminate" the pending transaction from channel 20?

**Comment by vsbogd** [comment]
@arturgontijo , thank you for reporting this. The reason is your etcd storage contains a key which locks transactions for the channel. Daemon aquired lock but did not release it. It might happen easily with old versions of daemon, it should not be the case since https://github.com/singnet/snet-daemon/pull/154 is merged. 

If you don't need the data you currently have in your etcd storage you can remove `storage-data-dir-1.etcd` folder it will eliminate the error. If you need the data then you can fix it by removing key `'/payment-channel/lock/{ID: 20}` from etcd. Right now it should be possible to use `etcdctl` tool for doing this. 

But I think we need an interface to manage it by simpler way. Something like "Operator UI" mentioned at https://github.com/singnet/snet-daemon/issues/29 .

**Comment by vsbogd** [comment]
Raised https://github.com/singnet/snet-daemon/issues/173

**Comment by arturgontijo** [comment]
> It might happen easily with old versions of daemon, it should not be the case since #154 is merged.

I'm pretty sure that the Daemon version running there is outdated (v0.1.2). I'll update it.

> If you don't need the data you currently have in your etcd storage you can remove storage-data-dir-1.etcd folder it will eliminate the error. If you need the data then you can fix it by removing key '/payment-channel/lock/{ID: 20} from etcd. Right now it should be possible to use etcdctl tool for doing this.

I'll do this, thanks!

**Comment by anandrgitnirman** [comment]
@arturgontijo let us know on any concerns, we could reopen this issue accordingly 
PR #187 will help you re open a channel if locked
PR  #191 was a fix put in to address an other possible scenario of channel getting locked

**Comment by vsbogd** [comment]
I have added issue https://github.com/singnet/snet-daemon/issues/209 to prevent channel is being locked after daemon is killed. It is probably the most frequent situation which such consequences.
