### ISSUE TITLE
daemon behind the NAT

### ISSUE THREAD

**Issue by astroseger** [singnet/snet-daemon#199]
It seems in the current version we cannot configure the daemon to work behind NAT.
In the case of working behind NAT we should set DAEMON_END_POINT to an internal endpoint. But  daemon search for group_id using DAEMON_END_POINT and it will not find it, because in metadata we have an external endpoint..

**Comment by anandrgitnirman** [comment]
Thanks @astroseger 
on Solution 1, I didn't understand this bit "GROUP_NAME can be specified only if DAEMON_END_POINT is not in metadata",  

Could we consider using Group_name as a mandatory field itself in Daemon? and get away from Daemon End point config in Daemon ? , we will then just have the Group Name and the port number as mandatory configs in daemon  ( this will be used by the daemon to start) 

@raamb  too for notification

**Comment by astroseger** [comment]
Correction: In the current version we have a problem only if external and internal ports are different. If ports are the same we should set DAEMON_END_POINT to the external endpoint and everything will work, because daemon will listen everything on this specific port.

Concerning "GROUP_NAME can be specified only if DAEMON_END_POINT is not in metadata" in Solution 1. It is only to prevent errors. If DAEMON_END_POINT is in metadata then GROUP_NAME shoudn't be specified. Or at least we should check that it is a correct GROUP_NAME (that DAEMON_END_POINT belongs to this group).

I'm ok with GROUP_NAME + PORT solution. But it will make old config invalid... It might be not ok now.

There is another solution... We could have an optional parameter DAEMON_PORT... If daemon port is not specified we get it from DAEMON_END_POINT.

**Comment by ksridharbabuus** [comment]
@astroseger The standard approach will be providing Daemon_port Parameter rather than combing the Port with Group_Name. 
I have one Question... Is all the Daemon should have the same port in the Group? 
We also had various other discussions in the past like a Load Balance / Routing Component and so on... Better to consider all possible scenarios while coming up with the solution.

**Comment by astroseger** [comment]
@ksridharbabuus 
I think that we shouldn't require that all daemons in the same payment group have the same port.

In any case, we should allow the possibility to have different external and internal ports (in case of NAT). It means that in config we should be able to set (directly or indirectly) two independent parameters:
- port. This port can be different from the port in metadata (in case then internal and external ports are different). 
- payment group.

**Comment by ferrouswheel** [comment]
I was curious how snetd works in AWS. The server I run stuff on has internal IPs for all its interfaces. i.e. the external IP is different to what the AWS instance can see. As mentioned above, if the ports are the same it surprisingly works somehow...

I think it's important to differentiate between:
- ip and port the daemon binds to, and
- the group it is part of for payments.

The daemon should have two configuration variables for these independent things.

I would suggest that the endpoints in the metadata ONLY be used by the client, since only the client needs to know external IP to connect to. The daemon doesn't need to know external IP/port... only the interface and port it needs to bind to.

At the moment [snetd will bind to 0.0.0.0](https://github.com/singnet/snet-daemon/blob/master/snetd/cmd/serve.go#L108) - i.e. all interfaces. This is a security risk. The user will be assuming that their server only binds to the interface with the IP in `DAEMON_END_POINT`. But servers in cloud environments usually have multiple networks.

If the user wants snetd to bind to all interfaces, they should specify `DAEMON_END_POINT` as `0.0.0.0:PORT`, otherwise they should specify the the local interface IP.

**Comment by ferrouswheel** [comment]
(Ideally, I don't think we should make NAT or routed network traffic a special case, I think the default configuration should always specify the payment group and local interface.)

**Comment by anandrgitnirman** [comment]
Fixed with PR #202
