### ISSUE TITLE
Starting Daemon with a different port from Service Metadata

### ISSUE THREAD

**Issue by arturgontijo** [singnet/snet-daemon#216]
Starting the Daemon with `"daemon_end_point": "0.0.0.0:5000",` for my `i3d-video-action-recognition` service (which has `"endpoint": "http://54.203.198.53:7005"` in its metadata) isn't throwing an error and the instance of Daemon keeps running.

I'm pretty sure that this behavior wasn't happening before, maybe with `v0.1.5`.

It would be good if Daemon returns an exit code 1 in this case.

**Comment by anandrgitnirman** [comment]
hi @arturgontijo 
this was intentionally done to resolve issue #199

**Comment by arturgontijo** [comment]
Ok, so to do a concise deploy test I should do what?
Maybe test the `heartbeat` at `daemon_end_point`?

**Comment by ferrouswheel** [comment]
This seems to be resolved or as-expected behaviour. Please reopen if needed!

**Comment by arturgontijo** [comment]
I think we should print, at least, a warning message showing that:

`snetd.config.json`:
```
{
    "daemon_end_point": "localhost:5000"
    ...
}
```

It's not matching the service's endpoint from metadata, for example:
```
{
    "endpoints": [
        {
            "group_name": "default_group",
            "endpoint": "localhost:5555"
        }
}
```

Sorry if this is already done.

**Comment by ferrouswheel** [comment]
I guess the point is that these, by design, will almost never match. The
interface bound to by daemon endpoint is rarely the public IP that clients
can see in the endpoints section of the service metadata.

I don't think we should add a warning that lots of people will see, because
then people stop paying attention to the important warnings.

But maybe there is a way to make it report the two values in the logs if
they are not already...

**Comment by arturgontijo** [comment]
Got it, this warning isn't so useful as I thought. Thanks!
