### ISSUE TITLE
Make authorization in state_service the same as in control_service

### ISSUE THREAD

**Issue by raamb** [singnet/snet-daemon#228]
@Dinesh2521 
I would also propose to change authorization strategy, similar to ```control_service``` (include block_number in the message to sign).

_Originally posted by @astroseger in https://github.com/singnet/snet-daemon/issues/220#issuecomment-471509808_

**Comment by raamb** [comment]
@astroseger creating this as a new issue to track it better.

**Comment by raamb** [comment]
Lets abstract the authorization logic out of control service and use it as a common piece across control service and state service

**Comment by astroseger** [comment]
Some points for discussion:

1. I do agree that authentication with ```block_number``` is not perfect and what @Dinesh2521 has originally proposed (with random message from the daemon which the client should sign (with some prefix, or course)) is more secure.  However the advantage of ```block_number``` authentication is that it eliminates one round of communication between client and service so it should be faster ( but obtaining of block_number might not be free) 

2. One can argue that we do not require authentication in state_service at all because service state information is not sensitive. However it potentially prevents some types of DoS and adds a little bit of privacy (however blockchain is open for everybody in any case).

**Comment by anandrgitnirman** [comment]
https://github.com/singnet/snet-daemon/pull/254
