### ISSUE TITLE
Operator UI - Display the current config of Deamon on a User Interface 

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-daemon#266]
The daemon will accept a public address when its started and any request signed by the private key corresponding to this address will be honoured by the daemon
We will have a standalone stateless dapp that can be used to access any daemon. Requests will be signed using the private key corresponding to the address the daemon was started off with.

One of the first functionality is to return the current configuration in Daemon
the following are to be Supplied
1) Name of the Attribute

2) Properties of the attribute
Current value of the Attribute
Whether this field is mandatory
Description 
Type of Attribute ( Example , url or number or string , etc) 
Is this Editable or not 
Will the Daemon have to be restarted or not 
What kind of grouping ( section in UI that this attribute belongs to) 

Which means every **leaf** level attribute will have the following properties 
```json
{
    "mandatory": false,
    "value": "",
    "description": "domain name for which ....)",
    "type": "string",
    "editable": true,
    "restart_daemon": false,
    "section": "certificate"
  }
```

As an example , picked two types of attributes and show what ** the Daemon will return** to the operator UI .
Please note **"payment_channel_storage_client"** is not a leaf level attribute and hence no properties are associated .
Please note we will define a new JSON constant of the format below ( the value will eventually be replaced by what is overridden from the config file supplied to Daemon to start) 

Even the default configuration will be derived from this json 

```json
{
  "auto_ssl_domain": {
    "mandatory": false,
    "value": "",
    "description": "domain name for which ....)",
    "type": "string",
    "editable": true,
    "restart_daemon": false,
    "section": "certificate"
  },

  "payment_channel_storage_client": {
    "connection_timeout": {
      "value": "5s",
      "description": "",
      "type": "string",
      "editable": true,
      "restart_daemon": false,
      "section": "general"
    },
    "request_timeout": {
      "value": "3s",
      "description": "",
      "type": "string",
      "editable": true,
      "restart_daemon": false,
      "section": "general"
    },
    "endpoints": {
      "value": [
        "http://127.0.0.1:2379"
      ],
      "description": "",
      "type": "url",
      "editable": true,
      "restart_daemon": false
    }
  }
}
```

**Comment by anandrgitnirman** [comment]
@ferrouswheel @raamb @vsbogd , request you to opine further

**Comment by raamb** [comment]
The reason for the leaf level attributes in the new json is to enable a richer UI.

**Comment by ferrouswheel** [comment]
@anandrgitnirman looks good to me

**Comment by vsbogd** [comment]
Am I right, that JSON above will be returned in `json_data` field? https://github.com/singnet/snet-daemon/blob/42bb94fc4b9c0b51d1bb84c6d5304759863d6fd1/config/configuration_service.proto#L68

If so what do you think about representing API in pure protobuf like:
``` protobuf
  message ConfigurationParameter {
    string name = 1;
    bool mandatory = 2;
    enum Type {
      STRING = 0;
      ...
    }
    message Value {
       oneof raw {
          string string = 1;
          int int = 2;
       }
    }
    Value value = 3;
    string description = 4;
    Type type = 5;
    bool editable = 6;
    bool restart_daemon = 7;
    string section = 8;
  }

  message ConfigurationResponse {
      //Signature will compromise of the below
      //(block_number,authentication_address,json_data)
      bytes signature = 1;

      //Holds the current configuration of Daemon and is sent back in the response.
      repeated ConfigurationParameter = 2;
  }
```

**Comment by anandrgitnirman** [comment]
thanks @vsbogd , are you suggesting we only have all leaf level details ? 
How does  for example , the below get represented  for example ? 
``` json
payment_channel_storage_client": {
    "connection_timeout": {
      ...
    }
```

``` go
 &ConfigurationParameter {
  name : "payment_channel_storage_client.connection_timeout",
...
``` 
}

**Comment by raamb** [comment]
@vsbogd thinking more about your suggestion, representing the configuration as a proto means that we will have to regenerate client side stubs when configuration changes. Advantage of using JSON is that its dynamic and the client can deserialize dynamically whenever there is a change. Let me know what you think

**Comment by vsbogd** [comment]
I have paid attention to this because such Protobuf/JSON API reminded me about our AI services. During Odyssey contest I have found that some services have string fields in messages descriptions which in fact represents JSON arrays and so on. In case of AI services it makes API unclear and complex to write a client: one needs to deal with both Protobuf and JSON. I will raise separate issue on this.

So the cons of mixing Protobuf and JSON I see:
- API is not clear; self descriptiveness of the Protobuf is lost;
- client/server side should deal with both Protobuf and JSON;

In general it is not clear why Protobuf is used at all, actually pure JSON could be used if it is more convenient to use it.

@raamb, regarding your point about Protobuf API regeneration: in fact Protobuf is able keeping backward compatibility as all fields are optional and you always can add field without affecting client and remove field if client doesn't require it. And even with JSON if change in protocol is incompatible then server logic update is required. The advantage of Protobuf in latter case (at least for languages with static typing) is that code incompatibility could be found during compilation stage.

@anandrgitnirman, yes, `Value` in fact could contain array of `ConfigurationParameter` or may be we should introduce `Configuration` message:
```protobuf
message Configuration {
  repeated ConfigurationParameter parameter = 1;
}
```

Saying all above I don't insist on using Protobuf and actually I am ready to listen to arguments why it is convenient to mix Protobuf and JSON in case of Operator UI. But right now it seems to me that using only JSON or only Protobuf would be simpler.

**Comment by raamb** [comment]
> Saying all above I don't insist on using Protobuf and actually I am ready to listen to arguments why it is convenient to mix Protobuf and JSON in case of Operator UI. But right now it seems to me that using only JSON or only Protobuf would be simpler.

@vsbogd I agree with all your points and there isn't value in mixing up protobuf and JSON. My preference is to keep this in pure JSON.

**Comment by ferrouswheel** [comment]
How much additional complexity does it insert into the daemon to manage JSON endpoints? My fear is that we have multiple authentication paths, and a larger surface area for attack.

If we already serve JSON/JSON-RPC then this point is moot. But if we're adding a JSON API just for the operator UI it's a bit weird.

It also requires us to manually validate JSON messages and provide proper errors (instead of letting grpc/protobuf do this on our behalf).

**Comment by raamb** [comment]
@ferrouswheel as I understand the Daemon was service JSON-RPC till recently (so no additional coding efforts) @anandrgitnirman please confirm.
W.r.t why JSON and not proto my main reason being that we will have a DApp that consumes this information and don't want the DApp to be recompiled and deployed every time the daemon configuration changes.

**Comment by ferrouswheel** [comment]
@raamb I'm not sure why the DApp would have to be recompiled? @vsbogd's proposal doesn't tie the protobuf to the naming of config variables. Also, as he mentioned: it's backwards compatible and you'd have to do work on the Dapp to take advantage of any new field changes whether it's JSON or a protobuf message.

**Comment by raamb** [comment]
@ferrouswheel consider that we add a new non-editable field in the daemon configuration. For the DApp to display this new field it would need to regenerate its stubs. Note that we have added some metadata to the structure to ensure that the DApp does not need to be touched upon to take advantage of some new fields (There may be some for which we do need to update the DApp anyways)

**Comment by raamb** [comment]
Also to note, I am not hung up on JSON, there is a huge advantage in keeping a consistent interface of grpc + proto for the daemon which I cannot argue much against.

**Comment by ferrouswheel** [comment]
@raamb Please check the above format again. Configuration parameters can be repeated as many times as necessary to cover all parameters as shown in the above proposal, `ConfigurationParameter` is a generic repeated field. No stubs need to be regenerated because the protobuf message doesn't limit how many parameters can be sent.

**Comment by raamb** [comment]
Of course!!!!!!!!!! My stupidity is immortalised in this thread. I missed that bit, apologies for creating some unnecessary confusion.

**Comment by ferrouswheel** [comment]
Haha - I've been there too ;-)
