### ISSUE TITLE
Improve daemon logging

### ISSUE THREAD

**Issue by ldub** [singnet/snet-daemon#27]
Currently snet-daemon only logs blockchain interactions and RPC calls 

Logging facility should be improved to include
1. Service API metrics
1. Service performance metrics
1. Instrumentation/Debugging
1. Support for sending logs to third party hosting/analysis service

**Comment by vsbogd** [comment]
Here is some proposal for the issue:
- at the moment [logrus](https://github.com/sirupsen/logrus) is used for logging 
- ```logrus``` has hooks to send some messages to the syslog or slack for example, new hooks can be added if it is needed
- to give client ability change logger settings these settings should be kept in external configuration file
- it is simpler to have one file for the whole snet-daemon configuration so logging settings should be added to the current JSON config
- to simplify configuration for the client we could introduce ```snet-daemon init --config <config_file>``` command to create ```<config_file>``` and print default config to it
- [logrus_mate](https://github.com/gogap/logrus_mate) could be used to load configuration and configure logger; logrus_mate can be configured to use JSON provider instead of default HOCON
- ```logrus_mate``` also has log rotation feature

**Comment by pennachin** [comment]
Makes sense to me.

**Comment by vsbogd** [comment]
Things which are done:
- init command added
- default configuration for logger added
- formatter type is configurable
- output type is configurable 
- log rotation supported
- log timestamps timezone is configurable

Things which are not done yet:
- support mail logrus hook as example of hook support
- add documentation

Improvement:
- use one value to configure logging timezone (at the moment one is used to configure logging timestamps and one to configure filename pattern)

**Comment by vsbogd** [comment]
I would propose closing this issue:
- adding metrics to snet-daemon is a subject of issue https://github.com/singnet/snet-daemon/issues/30
- current logger configuration allows adding additional loggers for metrics if it is required
- support for sending logs to the 3rd party services is implemented, new services can be easily added

**Comment by pennachin** [comment]
Agreed.
