### ISSUE TITLE
Commands to Manage operations on free call users

### ISSUE THREAD

**Issue by anandrgitnirman** [singnet/snet-daemon#456]
With free call usage now being maintained by Daemon , you should ideally give the Service providers option to view the list of all free call users for your service,
 also give an option to release any locked state of the user
and an option to re set the counter ( i.e allow the user to make more calls)

**Comment by vsbogd** [comment]
> We should also give an option to release any locked state of the user
@anandrgitnirman could you please explain it further. What kind of locked state do you mean?

**Comment by anandrgitnirman** [comment]
> kind of locked state do you mea

while updating the state of the free call, we use the same approach as that of channels, first acquire a lock and then once the service call is successful , update the calls made and release the lock . We have noticed from past experience that a channel can get locked ( since the concept is similar on how we use locks for free call usage update, there can be potential risk that the user gets locked too  LockStorage) ,

**Comment by vsbogd** [comment]
BTW, for the free-calls feature it would be simpler to decrement free-calls counter atomically before returning the result. In such case locking is not required. What do you think?

**Comment by anandrgitnirman** [comment]
> BTW, for the free-calls feature it would be simpler to decrement free-calls counter atomically before returning the result. In such case locking is not required. What do you think?

when service provider changes the free calls allowed , it becomes tricky to manager this , when we decrement no ? .. In which case we could say .. increment the number of free calls made before returning the result ., however . we also wanted to mirror the behaviour of paid calls ( for example when a request is currently in progress, we lock the  channel state offchain and other requests that did not get the lock can't proceed further ) .. similarl will be the case for free calls

**Comment by vsbogd** [comment]
> however . we also wanted to mirror the behaviour of paid calls ( for example when a request is currently in progress, we lock the channel state offchain and other requests that did not get the lock can't proceed further ) .. similarl will be the case for free calls

Well, I don't see a clear reason to reproduce payment channel calls behavior. I didn't find a way to apply payments without locking. It is the only reason why lock is used in `escrow` calls. In `free-calls` case as you mentioned we can increment number of calls made. We already have `CompareAndSwap` operation in `AtomicStorage` interface to implement such things easily.

I don't insist, my intention was to clarify whether fixing this issue is much simpler than implementing non-blocking `free-calls`. If it is not true than implementing non-blocking algorithm for `free-calls` makes more senses.
