### ISSUE TITLE
Latest official release

### ISSUE THREAD

**Issue by glautervl** [singnet/snet-daemon#67]
Today we are using the version number on the filename like snetd-0.1.0.tar.gz and we need to put this specific version number in the deployment process..

Would be great if have a easy way to download the latest stable version renaming the file to snetd-latest.tar.gz. 

It will help us to always use that version on our services.

**Comment by ferrouswheel** [comment]
Another option is to have a upstream docker image with an `ARG` specifying the daemon version to use, then you'd only have to update one docker image.

I think eventually we should be referring to specific daemon versions in docker builds. But until everything stabilises and our semantic version number reflects whether breaking API changes have been made, this will save service developers a lot of time!

**Comment by ferrouswheel** [comment]
The other nice thing about `ARG` is that you can override this while building the docker image ([see build arguments here](https://docs.docker.com/engine/reference/commandline/build)). So the default could be to build with `snetd-latest`, but if you want a stable build then you can override with a specific version.

**Comment by ramongduraes** [comment]
I like the docker image idea but I usually build my Dockerfiles using upstream images from deep learning frameworks (i.e. CNTK / specific versions of pytorch + nvidia-cuda + cudnn) which are way harder to get to work properly from scratch. Standardizing daemon releases seems like the way to go for me!

**Comment by vsbogd** [comment]
Btw, latest release link is supported by GitHub.com out of the box, for instance for daemon it will be: https://github.com/singnet/snet-daemon/releases/latest
At the moment this link shows the list of releases but the reason is we don't have any release which is not marked as "pre-release". As soon as we will have one it will be available by the link above.

**Comment by vsbogd** [comment]
I think we need just start publishing release without marking them "pre-release", @raamb , what do you think?

**Comment by vsbogd** [comment]
Then one can use https://api.github.com/repos/singnet/snet-daemon/releases/latest to get release JSON and parse release tarball link from it.

**Comment by arturgontijo** [comment]
We can also use the Github API to get the latest release [API-latest](https://api.github.com/repos/singnet/snet-daemon/releases/latest). 
With the "pre-release" tag is it possible to download it directly using https://github.com/singnet/snet-daemon/releases/latest ?

**Comment by vsbogd** [comment]
@arturgontijo , as far as I understand  we cannot use "latest" to get "pre-releases".

**Comment by arturgontijo** [comment]
So we have 2 options:
- Publish a "latest" release with every new version so the link:
 https://github.com/singnet/snet-daemon/releases/download/latest/snetd-latest.tar.gz
starts the download of the current version.
- Use the Github API to get the current version download link.

I'm ok with both options, btw the second one is already "done".
But to keep a standard on this, lets agree to use one on all services.

PS: And don't forget to keep the folder structure, to avoid deploy errors at:
`cp ./extracted_folder/snetd-XXX /dest/snetd`

**Comment by raamb** [comment]
Yes, pre-release will not be returned by the latest API. 
I was going with the notion of latest meaning a full production release and hence marking all releases as pre-release. But given that the entire platform is in a beta state, I guess its ok to just have this marked as the latest. In fact I see that we have done this in the past.

@vsbogd I have marked this as the latest now, as you suggested we can go with this convention across the board.

**Comment by raamb** [comment]
@arturgontijo Lets go with first option - Publish a latest release with every new version.
However lets come up with a better folder structure. Not sure we need to include all builds under one folder, we can consider creating a different folder per platform.

**Comment by vsbogd** [comment]
In fact packaging script already has folder structure, see https://github.com/singnet/snet-daemon/blob/master/scripts/package , we just need to use it for building release packages

**Comment by vsbogd** [comment]
@raamb, my comment was only about making package structure consistent across releases as for now different releases has different folder structure. I agree that is is not necessary having one package with binaries for all platforms.

Regarding package format, as user of different native apps I see two main options: 
(1) app maintainer creates package for your system (.deb for debian, .rpm for RedHat, etc); for all other systems maintainer publishes binary file and sources
(2) app maintainer uses universal package format;
I don't like option (2) because it forces you as user using some new packaging system which looks good for maintainer but probably not for you. I like option (1) because if your system is popular or you have latest libraries version it doesn't require anything special from you. I also agree that option (1) is more complex for maintainer. From this perspective I would prefer sharing daemon as binary file.

Regarding `npm` I don't see strong reasons for using it here as daemon binary doesn't have dependencies.

**Comment by raamb** [comment]
Option 1 would be ideal, no doubt. In the immediate term can we standardize the binaries in the format 
snet-daemon-<version>-<os>-<architecture>.tar.gz
We will do this across all our repos.

**Comment by vinthedark** [comment]
The ```snet-daemon-<version>-<os>-<architecture>.tar.gz``` format is been followed as a part of release process and will commence from next release.

**Comment by vsbogd** [comment]
@vinthedark, how and where snet-daemon release process is described? Do we have shell script to release binaries or it is manual instruction? Where one can find it?
